name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: rustup update

      - name: Install cosign
        uses: sigstore/cosign-installer@main

      - name: Extract Version from Cargo.toml
        id: version
        run: |
          # Extract the version from Cargo.toml
          VERSION=$(grep -m1 '^version =' Cargo.toml | cut -d '"' -f 2)
          echo "Extracted version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Build
        run: cargo build --release

      - name: Sign the binaries
        run:
          cosign sign-blob -y --output-signature
          target/release/CapsWitch.exe.sig target/release/CapsWitch.exe

      - name: Upload the binaries
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }} # Use the version from Cargo.toml
          generate_release_notes: true # Automatically generate release notes
          files: |
            target/release/CapsWitch.exe
            target/release/CapsWitch.exe.sig
